import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("books.csv")
print("========== FIRST 5 ROWS ==========")
print(data.head())
print("\n========== LAST 5 ROWS ==========")
print(data.tail())
print("\n========== DATASET SHAPE ==========")
print(data.shape)
print("\n========== COLUMN NAMES ==========")
print(data.columns)
print("\n========== DATA TYPES ==========")
print(data.dtypes)
print("\n========== DATASET INFORMATION ==========")
print(data.info())
print("\n========== MISSING VALUES ==========")
print(data.isnull().sum())
print("\n========== DUPLICATE VALUES ==========")
print(data.duplicated().sum())
data["Price"] = data["Price"].str.replace("£", "", regex=False)
data["Price"] = data["Price"].astype(float)
print("\n========== SUMMARY STATISTICS ==========")
print(data.describe())
print("\nHighest Price :", data["Price"].max())
print("Lowest Price  :", data["Price"].min())
print("Average Price :", round(data["Price"].mean(), 2))
print("\n========== RATING COUNTS ==========")
print(data["Rating"].value_counts())
plt.figure(figsize=(8,5))
plt.hist(data["Price"], bins=10)
plt.title("Distribution of Book Prices")
plt.xlabel("Price (£)")
plt.ylabel("Number of Books")
plt.show()
plt.figure(figsize=(6,5))
data["Rating"].value_counts().plot(kind="bar")
plt.title("Book Ratings")
plt.xlabel("Rating")
plt.ylabel("Number of Books")
plt.show()
plt.figure(figsize=(6,6))
data["Rating"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%"
)
plt.title("Book Rating Distribution")
plt.ylabel("")

plt.show()
